### PR TITLE
Feature/add templating

### PR DESCRIPTION
**Pull request by jimCresswell**
Add basic templating using Handlebars and the hbs adapter for Express.

### CODE REVIEW

**Comment by sponte** [comment]
Failing tests :) @jimCresswell

**Comment by jimCresswell** [comment]
that is so cool

**Comment by jimCresswell** [comment]
@sponte fixed the tests, it was a bad assumption about page content... definitely my bad for not running the tests. When we start using Gulp we can have the tests run on file change.

**Comment by sponte** [comment]
Merge conflict @jimCresswell

**Comment by jimCresswell** [comment]
Yes there was

**Pull request merged**
