### PR TITLE
Adding ba.com feature files for demo

### PR DESCRIPTION
**Pull request by sponte**

### CODE REVIEW

**Comment by sponte** [comment]
This is absolutely amazing @jimCresswell https://oss-specs-specs-eu-pr-55.herokuapp.com/

**Comment by jimCresswell** [comment]
That is good! I deleted the comment because of the URL.

**Comment by sponte** [comment]
The one mentioned in the notification sponte deployed to oss-specs-specs-eu-pr-55 2 hours ago :)?

**Comment by jimCresswell** [comment]
@sponte now this demo is done we should kill this merge request and remove the branch.

**Comment by sponte** [comment]
Agreed.

**Pull request closed without merging**
