### PR TITLE
Pull in all client side dependencies

### PR DESCRIPTION
**Pull request by jimCresswell**
* Use Bower.
* Pull in client side dependencies with Bower.
* Add routing logic to use Bower components in browser.

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte `npm install` should also run `bower install` in the post-install step.

**Comment by sponte** [comment]
Build fails to deploy on heroku - might be due to dependency being a dev dependency and heroku:

```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  unspecified
       engines.npm (package.json):   unspecified (use default)
       
       Resolving node version (latest stable) via semver.io...
       Downloading and installing node 4.2.1...
       Using default npm version: 2.14.7
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Pruning any extraneous modules
       Installing node modules (package.json)
       
       > nodegit@0.5.0 install /tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158/node_modules/nodegit
       > node lifecycleScripts/install
       
       [nodegit] Fetching binary from S3.
       [nodegit] Completed installation successfully.
       
       > oss-specs@0.12.10 postinstall /tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158
       > bower install
       
       sh: 1: bower: not found
       
       npm ERR! Linux 3.13.0-57-generic
       npm ERR! argv "/tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158/.heroku/node/bin/node" "/tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158/.npmrc"
       npm ERR! node v4.2.1
       npm ERR! npm  v2.14.7
       npm ERR! file sh
       npm ERR! code ELIFECYCLE
       npm ERR! errno ENOENT
       npm ERR! syscall spawn
       npm ERR! oss-specs@0.12.10 postinstall: `bower install`
       npm ERR! spawn ENOENT
       npm ERR!
       npm ERR! Failed at the oss-specs@0.12.10 postinstall script 'bower install'.
       npm ERR! This is most likely a problem with the oss-specs package,
       npm ERR! not with npm itself.
       npm ERR! Tell the author that this fails on your system:
       npm ERR!     bower install
       npm ERR! You can get their info via:
       npm ERR!     npm owner ls oss-specs
       npm ERR! There is likely additional logging output above.
       
       npm ERR! Please include the following file with any support request:
       npm ERR!     /tmp/build_c9a15f84c0f16925ceb8c75c8152f623/oss-specs-specs-7891158/npm-debug.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - Node version not specified in package.json
       https://devcenter.heroku.com/articles/nodejs-support#specifying-a-node-js-version
       
       - Bower may not be tracked in package.json
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app
```

Trying with bower as standard dep

**Comment by sponte** [comment]
Ok, @jimCresswell this seemed to have worked. I'll assign to you as I am not sure whether moving bower to a standard dependency is a right thing to do.

**Comment by jimCresswell** [comment]
I would have classed Bower as a dev dependency, and I think that is how it is supposed to be used, however because we are not creating a build but driving everything directly off the source code (and because the build failed without your change) I guess Bower is a production dependency in this case! That can change once we are generating a build. Good spot!

**Pull request merged**
