### PR TITLE
Provide UI hints

### PR DESCRIPTION
**Pull request by jimCresswell**
* Better colour highlighting of interactive elements.
* Help message tool tips.

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte I bumped the version. Also, I can't reproduce the rendering issue when serving from my machine, can you accept the merge so we can see if the deployed version does this?

**Comment by sponte** [comment]
Let's try to reproduce on my local today. I don't want to merge potentially unstable code

**Comment by jimCresswell** [comment]
@sponte :boom: :exclamation:

**Comment by sponte** [comment]
@jimCresswell well done!

**Pull request merged**
