### PR TITLE
Hide tags by default

### PR DESCRIPTION
**Pull request by jimCresswell**
* Hide tags by default.
* Allow tags to be toggled.
* Tweak and standardise small screen view across layouts.

### CODE REVIEW

**Comment by sponte** [comment]
The button looks a bit out of place when viewed on a wide screen:

image

Could you align it to match feature file boundary?

**Comment by jimCresswell** [comment]
@sponte amazing, I shall fix that.

**Comment by jimCresswell** [comment]
@sponte that should do it.

**Comment by jimCresswell** [comment]
Hoozah!

**Pull request merged**
