### PR TITLE
WIP: Collapse details on feature pages by default

### PR DESCRIPTION
**Pull request by jimCresswell**
and add collapse-expand button for them.

### CODE REVIEW

**Comment by jimCresswell** [comment]
Addresses #153

**Comment by sponte** [comment]
It would be nice to be able to expand individual scenarios on their own. Imagine scrolling thorough a really long list and wanting to see a scenario. you'd have to go back up and expand all and then you'd need to find scenario again.

Also - when scenarios are collapsed, they blend in with each other. Could you separate them somehow?

**Comment by jimCresswell** [comment]
Sure, I can make them individually expandable.

Can you attach an image of the blending and say which browser you are using?

**Comment by sponte** [comment]
sorry, didn't make it clear. The scenarios don't actually blend in together but there is no visual separation between them:

image

**Comment by jimCresswell** [comment]
Ahh, sure, not problem... I agree, the list does not track well.

**Comment by jimCresswell** [comment]
Okay, we have increased visual separation in the collapsed list and toggling individual scenarios is half done. I'll finish this off tomorrow.

**Comment by jimCresswell** [comment]
@sponte ready for review.

**Comment by jimCresswell** [comment]
@sponte merge conflict resolved.

**Comment by sponte** [comment]
Sorry to be a pain but could you add hand cursor when hovering over scenarios?

**Comment by jimCresswell** [comment]
Yup, done.

**Pull request merged**
