### PR TITLE
Adding Aptfile

### PR DESCRIPTION
**Pull request by sponte**
This should fix running on heroku

### CODE REVIEW

**Comment by jimCresswell** [comment]
```text
-----> Apt app detected

WARNING: This buildpack is no longer maintained.

Please choose a different buildpack or go to https://github.com/ddollar/heroku-buildpack-apt

and fork it to your own account.

This buildpack will cease to function at the stroke of midnight on January 1, 2017.

 !     Push rejected, failed to compile Apt app.

 !     Push failed
```

**Comment by jimCresswell** [comment]
Is it to do with libgit and its odd needs?

**Comment by sponte** [comment]
No, I don't think so. Let me merge this as this won't cause any problems with the app but it's difficult to test inside Heroku's review apps

**Comment by jimCresswell** [comment]
Okey dokey

**Pull request merged**
