### PR TITLE
Switching nodegit to an exact version.

### PR DESCRIPTION
**Pull request by jimCresswell**

### CODE REVIEW

**Comment by sponte** [comment]
Is this suppose to help with Heroku?

**Comment by jimCresswell** [comment]
Potentially, just curious

**Comment by sponte** [comment]
nope ;( https://oss-specs-specs-eu-pr-129.herokuapp.com/

**Comment by jimCresswell** [comment]
But the tests passed?

**Comment by sponte** [comment]
Yeah, it works on OSX but not heroku :(

https://papertrailapp.com/systems/oss-specs-specs-eu-pr-127/events?r=584297329772003328-585077803268243465

**Comment by jimCresswell** [comment]
Deployed with Nodegit 0.5.0 ... breaks the code though. Closing this branch and doing the upgrade and fixes in #127

**Pull request closed without merging**
