### PR TITLE
Edit button on file pages

### PR DESCRIPTION
**Pull request by jimCresswell**
Please merge after #212 .

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte this is ready to go.

**Comment by sponte** [comment]
Should I be expecting to see edit button for markdown and other file types? If so this is not happening in our test app.

**Comment by jimCresswell** [comment]
In the file view, not on the project view...

**Comment by jimCresswell** [comment]
No feedback yet, let's merge and iterate.

**Comment by sponte** [comment]
You sure? Did we not get customer feedback in the end?

**Comment by jimCresswell** [comment]
I don't think so, not on this.

**Comment by jimCresswell** [comment]
I was going to add the button to all file types on the project page, let me do that first.

**Comment by jimCresswell** [comment]
@sponte okay, edit buttons everywhere.

**Comment by sponte** [comment]
@jimCresswell edit buttons don't appear on empty and broken features.

**Comment by jimCresswell** [comment]
Thanks! I'll have a look at that tomorrow.

**Pull request merged**
