### PR TITLE
Persist project page burger menu state

### PR DESCRIPTION
**Pull request by jimCresswell**

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte can you bump the version when you want to accept?

**Comment by sponte** [comment]
@jimCresswell happy to merge that in but could you make expanded menu look a bit more isolated? Once reloaded the "burger" looks lonely and it's hard to tell what it controls:

image

**Comment by jimCresswell** [comment]
Okay, things are more grouped now.

**Comment by jimCresswell** [comment]
@sponte ready for review. Could you bump the version when you want to merge please?

**Comment by sponte** [comment]
sorry to be a pain - we now have lost valuable vertical space when moving burger button. I really liked the way it composed itself into the divider line. If we moved the button and put repo controls into some kind of a container, what do you think about below:

image

**Comment by jimCresswell** [comment]
Do you mean that because the button is above the content controls that the list starts further down the page now? I'm all for making the controls visually distinct in the way you suggest but that won't affect where the button is. Am I missing something?

**Comment by sponte** [comment]
There are two parts to it now. The surrounding box and background to make the controls distict but also the button which I think was in perfect place before. Could you move it back?

**Comment by jimCresswell** [comment]
Short answer yes, long answer no but I can make it look like I did.

**Pull request merged**
