### PR TITLE
Project update button

### PR DESCRIPTION
**Pull request by jimCresswell**
Add a button to the project UI which causes a Git pull followed by a UI update.

### CODE REVIEW

**Comment by jimCresswell** [comment]
Implements #94

**Comment by jimCresswell** [comment]
Don't merge, found an issue.

**Comment by jimCresswell** [comment]
Okay, fixed.

**Comment by sponte** [comment]
After clicking update button, project gets duplicated and displayed without a name:

image

**Comment by jimCresswell** [comment]
The final commit should have fixed that, maybe it needs to be redeployed?

**Comment by sponte** [comment]
Ok, found an issue - teamcity was not running. Need to wait for it to be catch up

**Pull request merged**
