### PR TITLE
Editing files

### PR DESCRIPTION
**Pull request by jimCresswell**
Working prototype for editing files.

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte this is a working prototype for editing files, ready for review and feedback.

**Comment by jimCresswell** [comment]
I'm happy for this to be merged in its current state. I imagine people will also want to be able to click through to the editing from the feature file page but we can add that later if people want it, this PR is enough for people to try it out.

**Comment by sponte** [comment]
@jimCresswell I get edit button but it just reloads the page. Also, it would be nice to have this button on the feature page itself as most of the time, you will want to edit a feature is after inspecting it in detail

**Comment by jimCresswell** [comment]
@sponte sure, I will take a look. I agree about having the button on the feature page but as per https://github.com/oss-specs/specs/pull/189#issuecomment-156445746 I'd like to do that as a further piece of work, albeit a high priority one.

**Comment by jimCresswell** [comment]
@sponte okay, I think this is ready for merge.

**Comment by jimCresswell** [comment]
@sponte I think it works now.

**Pull request merged**
