### PR TITLE
Specify beginnings of directory paths to hide in the UI

### PR DESCRIPTION
**Pull request by jimCresswell**

### CODE REVIEW

**Comment by jimCresswell** [comment]
@sponte currently this setting will affect all projects, which is probably not desirable.

**Comment by jimCresswell** [comment]
@sponte thinking about how to specify paths to hide in the UI for different projects... this is really specific to the project in question, so maybe it should be in a file in that project? I don't like the idea of adding a specs configuration file to projects, but I can't think of another way to do it right now.

Maybe this needs to be something we specify through the UI, but in that case it would be an directories-to-include list rather than a parts of directory paths to hide list.

Food for thoughts. I'm happy for the current implementation to be merged if it helps with our specific case for the time being.

**Comment by sponte** [comment]
@jimCresswell I actually really like the idea of configuring specs from projects. Most public services do that alreayd .travis .heroku etc. Go for it!

**Comment by jimCresswell** [comment]
@sponte once the tests are passing can we merge this work first and then add support for configuration files in another branch?

**Comment by sponte** [comment]
@jimCresswell of course

**Comment by jimCresswell** [comment]
I'll fix the conflicts

**Comment by sponte** [comment]
@jimCresswell can we please hide the path when we have files directly under it?

image

Example above is showing current implementation when hide parameter was set to features. I would expect readme.md and example.md to be hidden

**Comment by jimCresswell** [comment]
This feature just modifies directory names, it doesn't change what files are displayed. b53cde2 modifies the replacement so that those files are shown as being in the root.

I actually think the right place to use this is in conjunction with the exclude path functionality and on a per view rather than per project basis - so that would be done via query parameters, then people can pass around those views. We can sort that out later though.

**Pull request merged**
